// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: health.proto

package health

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckReadyRequest is the payload sent to check the ready state
type CheckReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReadyRequest) Reset() {
	*x = CheckReadyRequest{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReadyRequest) ProtoMessage() {}

func (x *CheckReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReadyRequest.ProtoReflect.Descriptor instead.
func (*CheckReadyRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

// CheckReadyResponse is the ready state payload returned to the client
type CheckReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReadyResponse) Reset() {
	*x = CheckReadyResponse{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReadyResponse) ProtoMessage() {}

func (x *CheckReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReadyResponse.ProtoReflect.Descriptor instead.
func (*CheckReadyResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

// CheckLiveRequest is the payload sent to check the live state
type CheckLiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLiveRequest) Reset() {
	*x = CheckLiveRequest{}
	mi := &file_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLiveRequest) ProtoMessage() {}

func (x *CheckLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLiveRequest.ProtoReflect.Descriptor instead.
func (*CheckLiveRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

// CheckLiveResponse is the live state payload returned to the client
type CheckLiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLiveResponse) Reset() {
	*x = CheckLiveResponse{}
	mi := &file_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLiveResponse) ProtoMessage() {}

func (x *CheckLiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLiveResponse.ProtoReflect.Descriptor instead.
func (*CheckLiveResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{3}
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\x15phogolabs.plex.health\x1a\x1cgoogle/api/annotations.proto\"\x13\n" +
	"\x11CheckReadyRequest\"\x14\n" +
	"\x12CheckReadyResponse\"\x12\n" +
	"\x10CheckLiveRequest\"\x13\n" +
	"\x11CheckLiveResponse2\xbd\x02\n" +
	"\fHeartbeatAPI\x12\x92\x01\n" +
	"\tCheckLive\x12'.phogolabs.plex.health.CheckLiveRequest\x1a(.phogolabs.plex.health.CheckLiveResponse\"2\x82\xd3\xe4\x93\x02,Z\x19B\x17\n" +
	"\x04HEAD\x12\x0f/heartbeat/live\x12\x0f/heartbeat/live\x12\x97\x01\n" +
	"\n" +
	"CheckReady\x12(.phogolabs.plex.health.CheckReadyRequest\x1a).phogolabs.plex.health.CheckReadyResponse\"4\x82\xd3\xe4\x93\x02.Z\x1aB\x18\n" +
	"\x04HEAD\x12\x10/heartbeat/ready\x12\x10/heartbeat/readyB1Z/github.com/phogolabs/plex/service/health;healthb\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_health_proto_goTypes = []any{
	(*CheckReadyRequest)(nil),  // 0: phogolabs.plex.health.CheckReadyRequest
	(*CheckReadyResponse)(nil), // 1: phogolabs.plex.health.CheckReadyResponse
	(*CheckLiveRequest)(nil),   // 2: phogolabs.plex.health.CheckLiveRequest
	(*CheckLiveResponse)(nil),  // 3: phogolabs.plex.health.CheckLiveResponse
}
var file_health_proto_depIdxs = []int32{
	2, // 0: phogolabs.plex.health.HeartbeatAPI.CheckLive:input_type -> phogolabs.plex.health.CheckLiveRequest
	0, // 1: phogolabs.plex.health.HeartbeatAPI.CheckReady:input_type -> phogolabs.plex.health.CheckReadyRequest
	3, // 2: phogolabs.plex.health.HeartbeatAPI.CheckLive:output_type -> phogolabs.plex.health.CheckLiveResponse
	1, // 3: phogolabs.plex.health.HeartbeatAPI.CheckReady:output_type -> phogolabs.plex.health.CheckReadyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
